name: Auto Release on List Update

on:
  push:
    paths:
      - 'list.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Convert list.txt to data.json
      run: npm run text2json
      
    - name: Generate certificates
      run: npm run start
      
    - name: Get repo name
      id: get_repo_name
      run: |
        REPO_NAME=$(grep 'github_repo_name' list.txt | awk -F': ' '{print $2}')
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT
        echo "Current directory contents:"
        ls -la
       
    - name: Check if folder exists
      run: |
        if [ ! -d "${REPO_NAME}" ]; then
          echo "::error::Folder ${REPO_NAME} does not exist!"
          exit 1
        fi
      
    - name: Zip folder
      run: |
        zip -r "${REPO_NAME}.zip" "${REPO_NAME}"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "${REPO_NAME}.zip"
        generate_release_notes: true
      
    - name: Debug list.txt
      run: |
        echo "list.txt content:"
        cat list.txt
        echo "Extracted REPO_NAME:"
        grep 'github_repo_name' list.txt | awk -F': ' '{print $2}'
