name: Auto Release on List Update

on:
  push:
    paths:
      - 'list.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Convert list.txt to data.json
      run: npm run text2json
      
    - name: Generate certificates
      run: npm run start
      
    - name: Get repo name and check folder
      run: |
        # 获取 REPO_NAME
        REPO_NAME=$(grep 'github_repo_name' list.txt | awk -F': ' '/github_repo_name/{print $2}')
        
        # 检查是否获取到 REPO_NAME
        if [ -z "${REPO_NAME}" ]; then
          echo "::error::Failed to get REPO_NAME from list.txt!"
          exit 1
        fi

        # 检查目录是否存在
        if [ ! -d "${REPO_NAME}" ]; then
          echo "::error::Folder ${REPO_NAME} does not exist!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi

        echo "REPO_NAME: ${REPO_NAME}"
        echo "Folder ${REPO_NAME} exists, proceeding with zip..."

    - name: Zip folder
      run: |
        zip -r "${REPO_NAME}.zip" "${REPO_NAME}"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "${REPO_NAME}.zip"
        generate_release_notes: true
      
    - name: Debug list.txt
      run: |
        echo "list.txt content:"
        cat list.txt
        echo "Extracted REPO_NAME:"
        grep 'github_repo_name' list.txt | awk -F': ' '{print $2}'
